### ISSUE TITLE
Errors when building from fresh pull

### ISSUE THREAD

**Issue by austinmao** [EcsRx/ecsrx.roguelike2d#1]
![image](https://cloud.githubusercontent.com/assets/6487975/20804306/3be17daa-b7a7-11e6-82f9-f9d05125641d.png)

**Comment by austinmao** [comment]
Internal error: Recursion detected while updating scripts (assembly index: 3)

Assets/Plugins/UniRx/Scripts/UnityEngineBridge/MainThreadDispatcher.cs(312,41): error CS0176: Static member `UniRx.MainThreadDispatcher.StartCoroutine(System.Collections.IEnumerator)' cannot be accessed with an instance reference, qualify it with a type name instead

Assets/Plugins/UniRx/Scripts/UnityEngineBridge/MainThreadDispatcher.cs(367,35): error CS0176: Static member `UniRx.MainThreadDispatcher.StartCoroutine(System.Collections.IEnumerator)' cannot be accessed with an instance reference, qualify it with a type name instead

**Comment by grofit** [comment]
Given you have issues raised on the main ecsrx project which seem to be related to your environment and not the project (https://github.com/grofit/ecsrx/issues/28) I would be led to believe that the problem you list there is giving you some problem here as those issues are all within UniRx not ecsrx code, so I would imagine you have some issue with your environment.

**Comment by grofit** [comment]
Closing this as assumed fixed, feel free to re-open if not.
